### ISSUE TITLE
Future request: Deactive PDP by SIG_TERM of sgnsemu.

### ISSUE THREAD

**Issue by amorting** [osmocom/openggsn#1]
Is it possible to add Deactive PDP context with send SIG_TERM to sgsnemu process ?

When sgsnemu process is terminated by SIG_TERM in current the active PDP Context stay on GGSN and destroyed after new PDP Context is activated  for the same IMSI ( tested on Huawei UGW9811/GGSN9811).

**Comment by zecke** [comment]
We simply mirror the project here (e.g. for people behind corporate firewalls that can't use the git protocol). You are free to send a patch to the OpenBSC or GPRS mailinglist. Otherwise I don't see anyone adding support to it.
